workflows:
  ios-native:
    name: Build iOS App (Xcode)
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build iOS App
        script: |
          xcodebuild \
            -project "YourProject.xcodeproj" \
            -scheme "YourScheme" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/Build/**/*.app
      - build/**/Build/**/*.ipa
